// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package statuspage

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/nycruz/pulumi-statuspage/sdk/go/statuspage"
// 	"github.com/pulumi/pulumi-statuspage/sdk/go/statuspage"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := statuspage.GetComponents(ctx, &GetComponentsArgs{
// 			PageId: local.Page_id,
// 			Filters: []GetComponentsFilter{
// 				GetComponentsFilter{
// 					Name: "name",
// 					Values: []string{
// 						"value_1",
// 						"value_2",
// 					},
// 				},
// 			},
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetComponents(ctx *pulumi.Context, args *GetComponentsArgs, opts ...pulumi.InvokeOption) (*GetComponentsResult, error) {
	var rv GetComponentsResult
	err := ctx.Invoke("statuspage:index/getComponents:getComponents", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComponents.
type GetComponentsArgs struct {
	Filters []GetComponentsFilter `pulumi:"filters"`
	// the ID of the page this component belongs to
	PageId string `pulumi:"pageId"`
}

// A collection of values returned by getComponents.
type GetComponentsResult struct {
	Components []GetComponentsComponent `pulumi:"components"`
	Filters    []GetComponentsFilter    `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// the ID of the page this component belongs to
	PageId string `pulumi:"pageId"`
}

func GetComponentsOutput(ctx *pulumi.Context, args GetComponentsOutputArgs, opts ...pulumi.InvokeOption) GetComponentsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetComponentsResult, error) {
			args := v.(GetComponentsArgs)
			r, err := GetComponents(ctx, &args, opts...)
			var s GetComponentsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetComponentsResultOutput)
}

// A collection of arguments for invoking getComponents.
type GetComponentsOutputArgs struct {
	Filters GetComponentsFilterArrayInput `pulumi:"filters"`
	// the ID of the page this component belongs to
	PageId pulumi.StringInput `pulumi:"pageId"`
}

func (GetComponentsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetComponentsArgs)(nil)).Elem()
}

// A collection of values returned by getComponents.
type GetComponentsResultOutput struct{ *pulumi.OutputState }

func (GetComponentsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetComponentsResult)(nil)).Elem()
}

func (o GetComponentsResultOutput) ToGetComponentsResultOutput() GetComponentsResultOutput {
	return o
}

func (o GetComponentsResultOutput) ToGetComponentsResultOutputWithContext(ctx context.Context) GetComponentsResultOutput {
	return o
}

func (o GetComponentsResultOutput) Components() GetComponentsComponentArrayOutput {
	return o.ApplyT(func(v GetComponentsResult) []GetComponentsComponent { return v.Components }).(GetComponentsComponentArrayOutput)
}

func (o GetComponentsResultOutput) Filters() GetComponentsFilterArrayOutput {
	return o.ApplyT(func(v GetComponentsResult) []GetComponentsFilter { return v.Filters }).(GetComponentsFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetComponentsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetComponentsResult) string { return v.Id }).(pulumi.StringOutput)
}

// the ID of the page this component belongs to
func (o GetComponentsResultOutput) PageId() pulumi.StringOutput {
	return o.ApplyT(func(v GetComponentsResult) string { return v.PageId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetComponentsResultOutput{})
}
