// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package statuspage

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/nycruz/pulumi-statuspage/sdk/go/statuspage"
// 	"github.com/pulumi/pulumi-statuspage/sdk/go/statuspage"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := statuspage.GetComponentGroups(ctx, &GetComponentGroupsArgs{
// 			PageId: local.Page_id,
// 			Filters: []GetComponentGroupsFilter{
// 				GetComponentGroupsFilter{
// 					Name: "name",
// 					Values: []string{
// 						"value_1",
// 						"value_2",
// 					},
// 				},
// 			},
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetComponentGroups(ctx *pulumi.Context, args *GetComponentGroupsArgs, opts ...pulumi.InvokeOption) (*GetComponentGroupsResult, error) {
	var rv GetComponentGroupsResult
	err := ctx.Invoke("statuspage:index/getComponentGroups:getComponentGroups", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComponentGroups.
type GetComponentGroupsArgs struct {
	Filters []GetComponentGroupsFilter `pulumi:"filters"`
	// the ID of the page this component belongs to
	PageId string `pulumi:"pageId"`
}

// A collection of values returned by getComponentGroups.
type GetComponentGroupsResult struct {
	ComponentGroups []GetComponentGroupsComponentGroup `pulumi:"componentGroups"`
	Filters         []GetComponentGroupsFilter         `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// the ID of the page this component belongs to
	PageId string `pulumi:"pageId"`
}

func GetComponentGroupsOutput(ctx *pulumi.Context, args GetComponentGroupsOutputArgs, opts ...pulumi.InvokeOption) GetComponentGroupsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetComponentGroupsResult, error) {
			args := v.(GetComponentGroupsArgs)
			r, err := GetComponentGroups(ctx, &args, opts...)
			var s GetComponentGroupsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetComponentGroupsResultOutput)
}

// A collection of arguments for invoking getComponentGroups.
type GetComponentGroupsOutputArgs struct {
	Filters GetComponentGroupsFilterArrayInput `pulumi:"filters"`
	// the ID of the page this component belongs to
	PageId pulumi.StringInput `pulumi:"pageId"`
}

func (GetComponentGroupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetComponentGroupsArgs)(nil)).Elem()
}

// A collection of values returned by getComponentGroups.
type GetComponentGroupsResultOutput struct{ *pulumi.OutputState }

func (GetComponentGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetComponentGroupsResult)(nil)).Elem()
}

func (o GetComponentGroupsResultOutput) ToGetComponentGroupsResultOutput() GetComponentGroupsResultOutput {
	return o
}

func (o GetComponentGroupsResultOutput) ToGetComponentGroupsResultOutputWithContext(ctx context.Context) GetComponentGroupsResultOutput {
	return o
}

func (o GetComponentGroupsResultOutput) ComponentGroups() GetComponentGroupsComponentGroupArrayOutput {
	return o.ApplyT(func(v GetComponentGroupsResult) []GetComponentGroupsComponentGroup { return v.ComponentGroups }).(GetComponentGroupsComponentGroupArrayOutput)
}

func (o GetComponentGroupsResultOutput) Filters() GetComponentGroupsFilterArrayOutput {
	return o.ApplyT(func(v GetComponentGroupsResult) []GetComponentGroupsFilter { return v.Filters }).(GetComponentGroupsFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetComponentGroupsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetComponentGroupsResult) string { return v.Id }).(pulumi.StringOutput)
}

// the ID of the page this component belongs to
func (o GetComponentGroupsResultOutput) PageId() pulumi.StringOutput {
	return o.ApplyT(func(v GetComponentGroupsResult) string { return v.PageId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetComponentGroupsResultOutput{})
}
