# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .component import *
from .component_group import *
from .get_component_groups import *
from .get_components import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_statuspage.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_statuspage.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "statuspage",
  "mod": "index/component",
  "fqn": "pulumi_statuspage",
  "classes": {
   "statuspage:index/component:Component": "Component"
  }
 },
 {
  "pkg": "statuspage",
  "mod": "index/componentGroup",
  "fqn": "pulumi_statuspage",
  "classes": {
   "statuspage:index/componentGroup:ComponentGroup": "ComponentGroup"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "statuspage",
  "token": "pulumi:providers:statuspage",
  "fqn": "pulumi_statuspage",
  "class": "Provider"
 }
]
"""
)
