// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as statuspage from "@pulumi/statuspage";
 *
 * const default = statuspage.getComponentGroups({
 *     pageId: local.page_id,
 *     filters: [{
 *         name: "name",
 *         values: [
 *             "value_1",
 *             "value_2",
 *         ],
 *     }],
 * });
 * ```
 */
export function getComponentGroups(args: GetComponentGroupsArgs, opts?: pulumi.InvokeOptions): Promise<GetComponentGroupsResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("statuspage:index/getComponentGroups:getComponentGroups", {
        "filters": args.filters,
        "pageId": args.pageId,
    }, opts);
}

/**
 * A collection of arguments for invoking getComponentGroups.
 */
export interface GetComponentGroupsArgs {
    filters?: inputs.GetComponentGroupsFilter[];
    /**
     * the ID of the page this component belongs to
     */
    pageId: string;
}

/**
 * A collection of values returned by getComponentGroups.
 */
export interface GetComponentGroupsResult {
    readonly componentGroups: outputs.GetComponentGroupsComponentGroup[];
    readonly filters?: outputs.GetComponentGroupsFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * the ID of the page this component belongs to
     */
    readonly pageId: string;
}

export function getComponentGroupsOutput(args: GetComponentGroupsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetComponentGroupsResult> {
    return pulumi.output(args).apply(a => getComponentGroups(a, opts))
}

/**
 * A collection of arguments for invoking getComponentGroups.
 */
export interface GetComponentGroupsOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetComponentGroupsFilterArgs>[]>;
    /**
     * the ID of the page this component belongs to
     */
    pageId: pulumi.Input<string>;
}
