// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as statuspage from "@pulumi/statuspage";
 *
 * const default = statuspage.getComponents({
 *     pageId: local.page_id,
 *     filters: [{
 *         name: "name",
 *         values: [
 *             "value_1",
 *             "value_2",
 *         ],
 *     }],
 * });
 * ```
 */
export function getComponents(args: GetComponentsArgs, opts?: pulumi.InvokeOptions): Promise<GetComponentsResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("statuspage:index/getComponents:getComponents", {
        "filters": args.filters,
        "pageId": args.pageId,
    }, opts);
}

/**
 * A collection of arguments for invoking getComponents.
 */
export interface GetComponentsArgs {
    filters?: inputs.GetComponentsFilter[];
    /**
     * the ID of the page this component belongs to
     */
    pageId: string;
}

/**
 * A collection of values returned by getComponents.
 */
export interface GetComponentsResult {
    readonly components: outputs.GetComponentsComponent[];
    readonly filters?: outputs.GetComponentsFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * the ID of the page this component belongs to
     */
    readonly pageId: string;
}

export function getComponentsOutput(args: GetComponentsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetComponentsResult> {
    return pulumi.output(args).apply(a => getComponents(a, opts))
}

/**
 * A collection of arguments for invoking getComponents.
 */
export interface GetComponentsOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetComponentsFilterArgs>[]>;
    /**
     * the ID of the page this component belongs to
     */
    pageId: pulumi.Input<string>;
}
